name: ewasterecycling
description: A eWaste Recycling App for Pakistan

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.2.3
  geolocator: ^10.0.0
  share_plus: ^6.3.0
  syncfusion_flutter_charts: ^22.1.40
  provider: ^6.0.5
  http: ^1.1.0
  dio: ^5.3.2
  geocoding: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/